import AppKit
import Foundation

public final class ClipboardMonitor {
    public static let shared = ClipboardMonitor()
    
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let pasteboard = NSPasteboard.general
    public var isPaused: Bool = false
    
    public static let defaultIgnoredBundleIds: [String] = [
        "com.agilebits.onepassword",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess"
    ]
    
    private init() {
        lastChangeCount = pasteboard.changeCount
    }
    
    public func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }
    
    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }
    
    private func checkPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        
        // Skip if monitoring is paused
        if isPaused {
            return
        }
        
        // Skip if self triggered paste/copy
        if PasteManager.shared.isSelfCopying {
            return
        }
        
        // Check frontmost app and privacy settings
        let frontApp = NSWorkspace.shared.frontmostApplication
        let bundleId = frontApp?.bundleIdentifier ?? ""
        
        if PrivacyManager.shared.isIgnored(bundleId: bundleId) {
            return
        }
        
        // Check for sensitive or transient pasteboard types
        let sensitiveTypes: [NSPasteboard.PasteboardType] = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("com.agilebits.onepassword"),
            NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        ]
        
        if let types = pasteboard.types, types.contains(where: { sensitiveTypes.contains($0) }) {
            return
        }
        
        // Check if item originates from Apple Universal Clipboard (Handoff / 接力)
        let remoteType = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
        let isRemote = pasteboard.types?.contains(remoteType) ?? false
        
        // Extract Source App metadata
        let appName: String
        let effectiveBundleId: String
        var appIconData: Data? = nil
        
        if isRemote {
            appName = "iPhone"
            effectiveBundleId = "com.apple.handoff"
            appIconData = createHandoffDeviceIcon()
        } else {
            appName = frontApp?.localizedName ?? "未知应用"
            effectiveBundleId = bundleId
            if let icon = frontApp?.icon {
                appIconData = resizeImage(icon, to: NSSize(width: 48, height: 48))?.tiffRepresentation
            }
        }
        
        // Parse Pasteboard item
        guard let item = parsePasteboard(appName: appName, bundleId: effectiveBundleId, iconData: appIconData) else {
            return
        }
        
        // Play sound and register item in AppState
        SoundManager.shared.playCopySound()
        AppState.shared.addNewItem(item)
    }
    
    private func parsePasteboard(appName: String, bundleId: String, iconData: Data?) -> ClipItem? {
        let itemID = UUID()
        
        // 1. Check for File content FIRST (Crucial: Finder sets public.tiff for files, which false-triggers image checks)
        var filePaths: [String] = []
        let filenamesType = NSPasteboard.PasteboardType("NSFilenamesPboardType")
        if let paths = pasteboard.propertyList(forType: filenamesType) as? [String], !paths.isEmpty {
            filePaths = paths
        } else if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            filePaths = urls.filter { $0.isFileURL }.map { $0.path }
        }
        
        if !filePaths.isEmpty {
            let validPaths = filePaths.filter { FileManager.default.fileExists(atPath: $0) }
            if !validPaths.isEmpty {
                var totalSize: Int64 = 0
                for path in validPaths {
                    if let attrs = try? FileManager.default.attributesOfItem(atPath: path),
                       let size = attrs[.size] as? Int64 {
                        totalSize += size
                    }
                }
                let fileUrls = validPaths.map { URL(fileURLWithPath: $0) }
                let firstFileName = fileUrls.first?.lastPathComponent ?? "文件"
                let title = validPaths.count == 1 ? firstFileName : "\(firstFileName) 等 \(validPaths.count) 个文件"
                
                // Extract file icon
                var fileAppIcon = iconData
                if let first = validPaths.first {
                    let fileIcon = NSWorkspace.shared.icon(forFile: first)
                    if let tiff = resizeImage(fileIcon, to: NSSize(width: 48, height: 48))?.tiffRepresentation {
                        fileAppIcon = tiff
                    }
                }
                
                return ClipItem(
                    id: itemID,
                    type: .file,
                    plainText: title,
                    sourceAppName: appName,
                    sourceAppBundleId: bundleId,
                    sourceAppIconData: fileAppIcon,
                    filePaths: validPaths,
                    fileCount: validPaths.count,
                    fileSize: totalSize
                )
            }
        }
        
        // 2. Check for Image content (pure bitmap or screenshots)
        if let image = NSImage(pasteboard: pasteboard),
           let tiffData = image.tiffRepresentation,
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            
            let width = Int(image.size.width)
            let height = Int(image.size.height)
            let caption = "图片 (\(width) × \(height))"
            
            // Save image to disk on background thread
            let saveID = itemID
            DispatchQueue.global(qos: .utility).async {
                _ = StorageManager.shared.saveImage(data: pngData, id: saveID)
            }
            
            // Register the item immediately with the expected filename
            let fileName = "\(itemID.uuidString).png"
            return ClipItem(
                id: itemID,
                type: .image,
                plainText: caption,
                sourceAppName: appName,
                sourceAppBundleId: bundleId,
                sourceAppIconData: iconData,
                imageFileName: fileName,
                imageWidth: width,
                imageHeight: height,
                fileSize: Int64(pngData.count)
            )
        }
        
        // 3. Check for String / Text content
        guard let string = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !string.isEmpty else {
            return nil
        }
        
        // Capture rich text representations (RTF and HTML)
        var rtfData = pasteboard.data(forType: .rtf)
        var htmlData = pasteboard.data(forType: .html)
        
        // If we have HTML but no RTF, synthesize RTF so Office / RTF-only apps can paste
        if rtfData == nil, let html = htmlData {
            if let attr = try? NSAttributedString(data: html, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil) {
                rtfData = try? attr.data(from: NSRange(location: 0, length: attr.length), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
            }
        }
        
        // If we have RTF but no HTML, synthesize HTML so WPS / Web / HTML-only apps can paste
        if htmlData == nil, let rtf = rtfData {
            if let attr = try? NSAttributedString(data: rtf, options: [.documentType: NSAttributedString.DocumentType.rtf], documentAttributes: nil) {
                htmlData = try? attr.data(from: NSRange(location: 0, length: attr.length), documentAttributes: [.documentType: NSAttributedString.DocumentType.html])
            }
        }
        
        // Check for Color pattern (#FFF, #FFFFFF, rgb(...), rgba(...))
        if let hex = extractColorHex(from: string) {
            return ClipItem(
                id: itemID,
                type: .color,
                plainText: hex,
                sourceAppName: appName,
                sourceAppBundleId: bundleId,
                sourceAppIconData: iconData,
                colorHex: hex
            )
        }
        
        // Check for URL
        if let url = URL(string: string), let scheme = url.scheme?.lowercased(), (scheme == "http" || scheme == "https") {
            let host = url.host ?? string
            return ClipItem(
                id: itemID,
                type: .link,
                plainText: string,
                sourceAppName: appName,
                sourceAppBundleId: bundleId,
                sourceAppIconData: iconData,
                linkURL: string,
                linkTitle: host
            )
        }
        
        // Check for Code
        if let lang = detectCodeLanguage(in: string) {
            return ClipItem(
                id: itemID,
                type: .code,
                plainText: string,
                richTextData: rtfData,
                htmlData: htmlData,
                sourceAppName: appName,
                sourceAppBundleId: bundleId,
                sourceAppIconData: iconData,
                codeLanguage: lang
            )
        }
        
        // Default Plain/Rich Text
        return ClipItem(
            id: itemID,
            type: .text,
            plainText: string,
            richTextData: rtfData,
            htmlData: htmlData,
            sourceAppName: appName,
            sourceAppBundleId: bundleId,
            sourceAppIconData: iconData
        )
    }
    
    // Color pattern helper
    private func extractColorHex(from string: String) -> String? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        // Match #RGB, #RGBA, #RRGGBB, #RRGGBBAA
        let hexPattern = "^#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"
        if trimmed.range(of: hexPattern, options: .regularExpression) != nil {
            return trimmed.uppercased()
        }
        // Match rgb(r, g, b)
        let rgbPattern = #"^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$"#
        if let regex = try? NSRegularExpression(pattern: rgbPattern, options: .caseInsensitive),
           let match = regex.firstMatch(in: trimmed, options: [], range: NSRange(location: 0, length: trimmed.utf16.count)) {
            if let rRange = Range(match.range(at: 1), in: trimmed),
               let gRange = Range(match.range(at: 2), in: trimmed),
               let bRange = Range(match.range(at: 3), in: trimmed),
               let r = Int(trimmed[rRange]), let g = Int(trimmed[gRange]), let b = Int(trimmed[bRange]) {
                return String(format: "#%02X%02X%02X", min(r, 255), min(g, 255), min(b, 255))
            }
        }
        return nil
    }
    
    // Heuristic Code Language Detection
    private func detectCodeLanguage(in string: String) -> String? {
        // Quick heuristics based on keywords and syntax
        if string.contains("func ") || string.contains("import SwiftUI") || string.contains("import Cocoa") || string.contains("guard let ") {
            return "Swift"
        }
        if string.contains("def ") || string.contains("import numpy") || string.contains("__main__") || (string.contains("import os") && string.contains("def ")) {
            return "Python"
        }
        if string.contains("const ") || string.contains("console.log") || string.contains("=>") || string.contains("function(") || string.contains("export default") {
            return "JavaScript"
        }
        if string.contains("<div") || string.contains("<!DOCTYPE html>") || string.contains("</span>") || string.contains("</a>") {
            return "HTML"
        }
        if string.contains("SELECT ") && (string.contains("FROM ") || string.contains("WHERE ")) {
            return "SQL"
        }
        if (string.hasPrefix("{") && string.hasSuffix("}")) || (string.hasPrefix("[") && string.hasSuffix("]")) {
            if (try? JSONSerialization.jsonObject(with: Data(string.utf8), options: [])) != nil {
                return "JSON"
            }
        }
        if string.contains("{\n") || string.contains(";\n") || string.hasPrefix("#!/bin/") {
            return "Code"
        }
        return nil
    }
    
    private func resizeImage(_ image: NSImage, to newSize: NSSize) -> NSImage? {
        let newImage = NSImage(size: newSize)
        newImage.lockFocus()
        image.draw(in: NSRect(origin: .zero, size: newSize), from: NSRect(origin: .zero, size: image.size), operation: .copy, fraction: 1.0)
        newImage.unlockFocus()
        return newImage
    }
    
    private func createHandoffDeviceIcon() -> Data? {
        let size = NSSize(width: 48, height: 48)
        let image = NSImage(size: size)
        image.lockFocus()
        
        let bgRect = NSRect(origin: .zero, size: size)
        let path = NSBezierPath(roundedRect: bgRect, xRadius: 10, yRadius: 10)
        NSColor.systemBlue.withAlphaComponent(0.12).setFill()
        path.fill()
        
        if let symbol = NSImage(systemSymbolName: "iphone.and.arrow.forward", accessibilityDescription: "接力设备") {
            let config = NSImage.SymbolConfiguration(pointSize: 22, weight: .medium)
                .applying(.init(paletteColors: [NSColor.systemBlue]))
            if let configured = symbol.withSymbolConfiguration(config) {
                let symSize = configured.size
                let symRect = NSRect(
                    x: (size.width - symSize.width) / 2,
                    y: (size.height - symSize.height) / 2,
                    width: symSize.width,
                    height: symSize.height
                )
                configured.draw(in: symRect)
            }
        }
        image.unlockFocus()
        return image.tiffRepresentation
    }
}
